export const SliderData = [
  {
    image:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/categories/linkTwo/130.jpg',
    image1:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/categories/category/Copper-90-Elbows-150000.jpg',
    image2:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/categories/category/Copper-45-Elbows-153000.jpg',
    image3:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/categories/category/Copper-90-Street-Elbows-147000.jpg',
    image4:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/categories/category/Copper-45-Street-Elbows-152000.jpg',
    image5:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/categories/category/Copper-x-Male-Adapters-138000.jpg',
    image6:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/categories/category/Copper-x-Female-Adapters-142000.jpg'
  },
  {
    image:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/products/large/31272-3.jpg',
    image1:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/products/large/31288-3.jpg',
    image2:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/products/large/31296-3.jpg',
    image3:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/categories/category/Copper-Tees-134000.jpg',
    image4:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/categories/category/Copper-Reducing-Tees-24632000.jpg',
    image5:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/categories/category/Copper-Couplings-144000.jpg',
    image6:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/categories/category/Copper-Reducer-Couplings-135000.jpg'
  },
  {
    image:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/categories/category/Copper-Fitting-Reducers-139000.jpg',
    image1:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/categories/category/Copper-Unions-131000.jpg',
    image2:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/categories/category/Copper-Caps-145000.jpg',
    image3:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/categories/category/90-Drop-Ear-Elbows-CxF-151000.jpg',
    image4:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/categories/category/Copper-90-Long-Turn-Elbows-1645000.jpg',
    image5:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/categories/category/Copper-90-Long-Turn-Street-Elbows-1646000.jpg',
    image6:
      'https://s3.amazonaws.com/s3.supplyhouse.com/images/categories/category/Copper-Couplings-Less-Stop-143000.jpg'
  }
];
